### ISSUE TITLE
Maintain typescript definitions in different repository/package

### ISSUE THREAD

**Issue by TimDaub** [TimDaub/connect-better-sqlite3#11]
As some people found functional bugs in this repository:

- #9 
- #10

@neodon, I had to fix them and started running into problems with the TypeScript definitions: https://github.com/TimDaub/better-sqlite3-session-store/actions/runs/2561580206

I don't use TypeScript personally and so I also wasn't sure what to do. My goal was to update the package functionally to npm. Hence in 7024dd77fefdda8a546cf8ba07a4ca657128fd9f, I removed TS support again. 

@neodon, please, if you still want to use with package with TypeScript, to make upgrading straightforward for me, if that's possible, release the type's definition in a separate repository and use this npm package as a dependency.

In that case, I can work on my code without having to deal with a language I don't know, and you can use yours. I can't be shipping non-functional code. Hope you understand.

Best,
Tim

**Comment by TimDaub** [comment]
I guess another option is where you re-add TypeScript support and I bump the patch version number...

**Comment by neodon** [comment]
Hey Tim, I completely understand.  Thank you for reaching out.  I'll have to give this some thought and figure out how to move forward, but it might take some time.

**Comment by nwesterhausen** [comment]
I was able to create a typing stub to provide a type for this library that TS seems happy with:

```ts
/** typing-stubs/better-sqlite3-session-store/index.d.ts **/
declare module "better-sqlite3-session-store" {
  import { Store, SessionData } from "express-session";
  
  export interface SqliteStore extends Store {
    get(sid: string, callback: (err: any, session?: SessionData | null) => void): void;
    set(sid: string, session: SessionData, callback?: (err?: any) => void): void;
    destroy(sid: string, callback?: (err?: any) => void): void;

    startInterval(): void;
    clearExpiredSessions(): void;
    createDb(): void;
  }

  type Constructor<T = {}> = new (...args: any[]) => T;

  function createSqliteStore(session: { Store: typeof Store }): Constructor<SqliteStore>;

  export default createSqliteStore;
}
```

I add the following to my `tsconfig.json` file so that typescript knows where to find the type definition:

```json
{
  "compilerOptions": {
    "typeRoots": ["./typing-stubs", "./node_modules/@types"]
  }
}
```
