### ISSUE TITLE
a working example

### ISSUE THREAD

**Issue by azermann** [TimDaub/connect-better-sqlite3#2]
Hi there i am new to this and need direction do you have a working demo or detailed document step by step guide where to start i want to make this in swift with firebase or in web with vue

**Comment by TimDaub** [comment]
Hey, thanks for reaching out. I'm not exactly sure if I can be of help. What exactly do you want to achieve?

This library is an extension of express' session. For details on the implementation, check: https://github.com/expressjs/session#session-store-implementation

**Comment by azermann** [comment]
Heya again thnx for reply i need an example of how to create and viewed a session in vue my goal is make an app which change color style or air plane seats, carpets in real time and show selected color of seat etc

**Comment by TimDaub** [comment]
Hey,

this repository hosts a session store for expressjs. I have no reason to assume vuejs has compatibility with express. I also never used Vuejs, so I'm not the right person to help.

But best of luck for finding an answer!
