### ISSUE TITLE
SqliteStore is not a constructor

### ISSUE THREAD

**Issue by moigamijunior** [TimDaub/connect-better-sqlite3#6]
import pkg from "better-sqlite3-session-store";
const {SqliteStore} = pkg(session)
const db = new sqlite("sessions.db", { verbose: console.log });

store: new SqliteStore({
    client: db, 
    expired: {
      clear: true,
      intervalMs: 900000 //ms = 15min
    }
  })

Is this the right way of using modules? Can you help me?

`TypeError: SqliteStore is not a constructor`

**Comment by TimDaub** [comment]
```
import StoreFactory from "better-sqlite-session-store"
const SqliteStore = StoreFactory(session)
```
