### ISSUE TITLE
cookie expire time does not match database expire time.

### ISSUE THREAD

**Issue by cerealbox** [TimDaub/connect-better-sqlite3#9]
after a new session inserts into the db using a 10 minute maxAge:
```
cookie: { 
   maxAge: 60 * 10 * 1000 // 10 minutes.
}
```
the cookie expire time does not match the 'expires' row in the sessions table:
`hfGQW3_8A0Q12Ob2EHGkFP4KLfJ9Lz0i | {"cookie":{"originalMaxAge":600000,"expires":"2022-03-25T16:43:21.968Z","httpOnly":true,"path":"/"},"role":"guest"} | 2022-04-01T15:13:21.968Z
`
the cookie expire time is correctly 10 minutes into the future but the 'expires' row is over a week into the future.

from the source, i believe the below is not true (or is no longer true):

```
       // NOTE: `Max-age` property in cookie is in unit seconds

      const now = new Date();
      const expire = add(now, { seconds: age }).toISOString();

```
the max-age property appears to be in milliseconds according to the docs:
http://expressjs.com/en/resources/middleware/session.html#:~:text=cookie.maxAge

**Comment by cerealbox** [comment]
to further clarify, this problem only happens in the `set()` method.
the `touch()` method will update the database row and rectify the expire time but if the server crashes first the expire time will remain incorrect.

**Comment by TimDaub** [comment]
Great observation. I interpret express's docs as you mention it. Also, taking a closer look at https://github.com/rawberg/connect-sqlite3/blob/c1779b37f99f1585fdedf83a803ca242662d0aeb/lib/connect-sqlite3.js#L17, we can also see that they use milliseconds.
